[2023-04-05T04:43:09.732+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:43:07.319655+00:00 [queued]>
[2023-04-05T04:43:09.742+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:43:07.319655+00:00 [queued]>
[2023-04-05T04:43:09.742+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T04:43:09.743+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-05T04:43:09.743+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T04:43:09.756+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): object_transformation.sql> on 2023-04-05 04:43:07.319655+00:00
[2023-04-05T04:43:09.763+0000] {standard_task_runner.py:55} INFO - Started process 376 to run task
[2023-04-05T04:43:09.767+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ELT', 'object_transformation.sql', 'manual__2023-04-05T04:43:07.319655+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpjpesistn']
[2023-04-05T04:43:09.768+0000] {standard_task_runner.py:83} INFO - Job 93: Subtask object_transformation.sql
[2023-04-05T04:43:09.829+0000] {task_command.py:389} INFO - Running <TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:43:07.319655+00:00 [running]> on host f5e703d34d7f
[2023-04-05T04:43:09.892+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=200300600@ucaribe.edu.mx
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ELT
AIRFLOW_CTX_TASK_ID=object_transformation.sql
AIRFLOW_CTX_EXECUTION_DATE=2023-04-05T04:43:07.319655+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-05T04:43:07.319655+00:00
[2023-04-05T04:43:09.894+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-05T04:43:09.895+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/demo && dbt run']
[2023-04-05T04:43:09.914+0000] {subprocess.py:86} INFO - Output:
[2023-04-05T04:43:12.295+0000] {subprocess.py:93} INFO - [0m04:43:12  Error importing adapter: No module named 'dbt.adapters.postgres'
[2023-04-05T04:43:12.296+0000] {subprocess.py:93} INFO - [0m04:43:12  Encountered an error while reading profiles:
[2023-04-05T04:43:12.296+0000] {subprocess.py:93} INFO -   ERROR: Runtime Error
[2023-04-05T04:43:12.296+0000] {subprocess.py:93} INFO -   Credentials in profile "demo", target "dev" invalid: Runtime Error
[2023-04-05T04:43:12.296+0000] {subprocess.py:93} INFO -     Could not find adapter type postgres!Defined profiles:
[2023-04-05T04:43:12.297+0000] {subprocess.py:93} INFO -  - demo
[2023-04-05T04:43:12.297+0000] {subprocess.py:93} INFO - For more information on configuring profiles, please consult the dbt docs:
[2023-04-05T04:43:12.297+0000] {subprocess.py:93} INFO - 
[2023-04-05T04:43:12.297+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/configure-your-profile
[2023-04-05T04:43:12.297+0000] {subprocess.py:93} INFO - 
[2023-04-05T04:43:12.298+0000] {subprocess.py:93} INFO - [0m04:43:12  Encountered an error:
[2023-04-05T04:43:12.298+0000] {subprocess.py:93} INFO - Runtime Error
[2023-04-05T04:43:12.298+0000] {subprocess.py:93} INFO -   Could not run dbt
[2023-04-05T04:43:12.512+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-05T04:43:12.524+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-05T04:43:12.528+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ELT, task_id=object_transformation.sql, execution_date=20230405T044307, start_date=20230405T044309, end_date=20230405T044312
[2023-04-05T04:43:12.550+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 93 for task object_transformation.sql (Bash command failed. The command returned a non-zero exit code 2.; 376)
[2023-04-05T04:43:12.585+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-05T04:43:12.603+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
