[2023-04-05T04:46:24.818+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:46:21.312935+00:00 [queued]>
[2023-04-05T04:46:24.827+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:46:21.312935+00:00 [queued]>
[2023-04-05T04:46:24.827+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T04:46:24.827+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-05T04:46:24.827+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T04:46:24.839+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): object_transformation.sql> on 2023-04-05 04:46:21.312935+00:00
[2023-04-05T04:46:24.845+0000] {standard_task_runner.py:55} INFO - Started process 156 to run task
[2023-04-05T04:46:24.849+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ELT', 'object_transformation.sql', 'manual__2023-04-05T04:46:21.312935+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpq9gaf8xw']
[2023-04-05T04:46:24.849+0000] {standard_task_runner.py:83} INFO - Job 97: Subtask object_transformation.sql
[2023-04-05T04:46:24.911+0000] {task_command.py:389} INFO - Running <TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:46:21.312935+00:00 [running]> on host bfa8d25d3169
[2023-04-05T04:46:24.975+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=200300600@ucaribe.edu.mx
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ELT
AIRFLOW_CTX_TASK_ID=object_transformation.sql
AIRFLOW_CTX_EXECUTION_DATE=2023-04-05T04:46:21.312935+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-05T04:46:21.312935+00:00
[2023-04-05T04:46:24.978+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-05T04:46:24.979+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/demo && dbt run']
[2023-04-05T04:46:24.995+0000] {subprocess.py:86} INFO - Output:
[2023-04-05T04:46:27.364+0000] {subprocess.py:93} INFO - [0m04:46:27  Running with dbt=1.4.5
[2023-04-05T04:46:27.380+0000] {subprocess.py:93} INFO - [0m04:46:27  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2023-04-05T04:46:28.173+0000] {subprocess.py:93} INFO - [0m04:46:28  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-04-05T04:46:28.173+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2023-04-05T04:46:28.173+0000] {subprocess.py:93} INFO - - models.demo.example
[2023-04-05T04:46:28.194+0000] {subprocess.py:93} INFO - [0m04:46:28  Found 1 model, 0 tests, 0 snapshots, 0 analyses, 291 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
[2023-04-05T04:46:28.200+0000] {subprocess.py:93} INFO - [0m04:46:28
[2023-04-05T04:46:28.314+0000] {subprocess.py:93} INFO - [0m04:46:28  Concurrency: 1 threads (target='dev')
[2023-04-05T04:46:28.315+0000] {subprocess.py:93} INFO - [0m04:46:28
[2023-04-05T04:46:28.324+0000] {subprocess.py:93} INFO - [0m04:46:28  1 of 1 START sql view model elt_dbt.object_transformation ...................... [RUN]
[2023-04-05T04:46:28.387+0000] {subprocess.py:93} INFO - [0m04:46:28  1 of 1 ERROR creating sql view model elt_dbt.object_transformation ............. [[31mERROR[0m in 0.06s]
[2023-04-05T04:46:28.434+0000] {subprocess.py:93} INFO - [0m04:46:28
[2023-04-05T04:46:28.435+0000] {subprocess.py:93} INFO - [0m04:46:28  Finished running 1 view model in 0 hours 0 minutes and 0.23 seconds (0.23s).
[2023-04-05T04:46:28.443+0000] {subprocess.py:93} INFO - [0m04:46:28
[2023-04-05T04:46:28.444+0000] {subprocess.py:93} INFO - [0m04:46:28  [31mCompleted with 1 error and 0 warnings:[0m
[2023-04-05T04:46:28.445+0000] {subprocess.py:93} INFO - [0m04:46:28
[2023-04-05T04:46:28.445+0000] {subprocess.py:93} INFO - [0m04:46:28  [33mDatabase Error in model object_transformation (models/object_transformation.sql)[0m
[2023-04-05T04:46:28.446+0000] {subprocess.py:93} INFO - [0m04:46:28    relation "dron_table.objects" does not exist
[2023-04-05T04:46:28.447+0000] {subprocess.py:93} INFO - [0m04:46:28    LINE 5: from dron_table.objects
[2023-04-05T04:46:28.447+0000] {subprocess.py:93} INFO - [0m04:46:28                 ^
[2023-04-05T04:46:28.448+0000] {subprocess.py:93} INFO - [0m04:46:28    compiled Code at target/run/demo/models/object_transformation.sql
[2023-04-05T04:46:28.449+0000] {subprocess.py:93} INFO - [0m04:46:28
[2023-04-05T04:46:28.450+0000] {subprocess.py:93} INFO - [0m04:46:28  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-04-05T04:46:29.057+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-05T04:46:29.068+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-05T04:46:29.071+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ELT, task_id=object_transformation.sql, execution_date=20230405T044621, start_date=20230405T044624, end_date=20230405T044629
[2023-04-05T04:46:29.085+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 97 for task object_transformation.sql (Bash command failed. The command returned a non-zero exit code 1.; 156)
[2023-04-05T04:46:29.117+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-05T04:46:29.140+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
